- name: Install basic packages
  apt:
    pkg:
      - gpg
    update_cache: yes

# Ubuntu
- name: Add repo (Ubuntu)
  apt_repository:
    repo: "ppa:cz.nic-labs/knot-dns"
    state: present
  when: ansible_distribution == "Ubuntu"

# Debian
- name: Add repo keys (Debian)
  apt_key:
    url: "https://deb.knot-dns.cz/apt.gpg"
    state: present
  when: ansible_distribution == "Debian"

- name: Add repo (Debian)
  apt_repository:
    repo: "deb https://deb.knot-dns.cz/knot/ {{ ansible_lsb.codename }} main"
    state: present
  when: ansible_distribution == "Debian"

# Debian Family (Debian, Ubuntu)
- name: Install knot (Debian/Ubuntu)
  apt:
    pkg:
      - knot
      - knot-dnsutils
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"
