- name: Install Knot
  include: install.yml

- name: Check variables when slave
  fail:
    msg: "{{ item }} is required in slave DNS server"
  when: not (knot_master | bool) and item is not defined
  loop:
    - knot_zone.master

- name: Create logging directory
  file:
    path: "{{ knot_log.target }}"
    state: directory
    owner: "{{ knot_user }}"
    group: "{{ knot_group }}"
    mode: 0775
  when: knot_log is defined

- name: Configure Knot
  template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
    mode: '640'
    owner: "{{ knot_user }}"
    group: "{{ knot_group }}"
    validate: "knotc -c %s conf-check"
  notify: restart_knot

- name: Enable and start knot
  service:
    name: "{{ knot_daemon }}"
    enabled: true
    state: started
