- name: Install Knot
  include: install.yml

- name: Create logging directories
  file:
    path: "{{ item.target | dirname }}"
    state: directory
    recurse: yes
    owner: "{{ knot_user }}"
    group: "{{ knot_group }}"
    mode: 0775
  when: knot_log is defined
  loop: "{{ knot_log }}"

- name: Create logging files
  file:
    path: "{{ item.target }}"
    state: touch
    owner: "{{ knot_user }}"
    group: "{{ knot_group }}"
    mode: 0775
  when: knot_log is defined
  loop: "{{ knot_log }}"

- name: Configure Knot
  template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
    mode: '640'
    owner: "{{ knot_user }}"
    group: "{{ knot_group }}"

- name: Check valid configuration
  command:
    cmd: 'knotc -c /etc/knot/knot.conf conf-check'
  register: conf_check_out

- name: Enable and restart knot
  service:
    name: "{{ knot_daemon }}"
    enabled: true
    state: restarted
  when: conf_check_out.rc == 0
